app:
  name: aether
  server: Development
webserver:
  port: 9000
  timeout: 10 # in second
  rate_limit: 10
database:
  tipe: core
  driver: mysql
  address: ${{ secrets.IP_DATABASE_DEV }}
  #  address: localhost
  username: ${{ secrets.DB_USERNAME_DEV }}
  password: ${{ secrets.DB_PASSWORD_DEV }}
  port: 3306
  name: ${{ secrets.DB_NAME_DEV }}
  maxidle: 10
  maxopen: 10
  maxidletime: 5
  maxlifetime: 10
  timeout: 5 # in second
jwt:
  key: ${{ secrets.JWT_SECRET_DEV }} 
  tokenexpiredtime: 360 # in minute
  refreshtokenexpiredtime: 365 # in days
timezone:
  timezone: Asia/Makassar # Asia/Jakarta, Asia/Makassar, Asia/Jayapura
log:
  level: trace # trace, debug, info, warn, error, fatal, panic
  levels:
    - info
    - warn
    - error